spring:
  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: keonjuu
  messages:
    basename: messages,errors
  servlet:
    multipart:
      enabled: true
      max-request-size: 1024MB
      max-file-size: 1024MB
  sql:
    init:
#      mode: always


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout=: 18000
  error:
    whitelabel:
      enabled: false

file:
  dir: C:\Users\User\Documents\fileDirectory\
