spring:
  jpa:
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
#    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: keonjuu
  messages:
    basename: messages,errors


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout=: 18000
  error:
    whitelabel:
      enabled: false

